django_movie/django_movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_movie/movie/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.MoviesView.as_view()),
    path("<slug:slug>/", views.MovieDeteilView.as_view(), name='movie_detail'),
    path("review/<int:pk>/", views.AddReview.as_view(), name="add_review")
]

django_movie/movie/models.py
from django.db import models
from datetime import date
from django.urls import reverse

class Category(models.Model):

    # Катигория фильмов

    name = models.CharField('Имя', max_length=150) #
    descriprions = models.TextField("Описания ") # TextFiled - текстовое поле 
    url = models.SlugField(max_length=150, unique=True) # SlugField - использвуется для url(s)
 
    # Возвращает  значение в виде строки
    def __str__(self):
        return self.name
    

    # Мета данные которые связываются с базой данных 
    class Meta:
        verbose_name = "Категория" # ед. число 
        verbose_name_plural = "Категория" 


class Actor(models.Model):

    # Категория актеров и режисеров

    name = models.CharField('Имя', max_length=150)
    age = models.PositiveSmallIntegerField('Возраст', default=0) # PositiveSmallIntegerField - значения от 0 до 32767
    descriprions = models.TextField("Описания ") # TextFiled - текстовое поле 
    imgae = models.ImageField('Изоброжения ', upload_to='actors/') # Сохраняет изображения в дериктории actors

    # Возвращает  значение в виде строки
    def __str__(self):
        return self.name
    

    # Мета данные которые связываются с базой данных 
    class Meta:
        verbose_name = "Актеры и Режисеры" # ед. число 
        verbose_name_plural = "Актеры и Режисеры" 


class Ganre(models.Model):

    # Жанры

    name = models.CharField('Имя', max_length=100)
    descriprions = models.TextField("Описания ") # TextFiled - текстовое поле 
    url = models.SlugField(max_length=150, unique=True) # SlugField - используется  для url(s)
    

    # Возвращает  значение в виде строки
    def __str__(self):
        return self.name


    # Мета данные которые связываются с базой данных 
    class Meta:
        verbose_name = "Жанры" # ед. число 
        verbose_name_plural = "Жанры" 


class Movie(models.Model):
    
    # Фильмы

    title = models.CharField('Название', max_length=150)
    tagline = models.CharField('Слоган', max_length=100, default='')
    descriprions = models.TextField("Описания ") # TextFiled - текстовое поле 
    poster = models.ImageField('Постер', upload_to='movies/') # сохроняет значение в дерикторий movies
    year = models.PositiveSmallIntegerField('Дата выхода', default=2018)
    county = models.CharField('Страны', max_length=50)
    directors = models.ManyToManyField(Actor, verbose_name='Режиссер', related_name='film_director') # ManyToManyField - Отношение многих ко многим
    actors = models.ManyToManyField(Actor, verbose_name="Актеры", related_name='film_actor') # ManyToManyField - Отношение многих ко многим
    gengers = models.ManyToManyField(Ganre, verbose_name="Жанры") # ManyToManyField - Отношение многих ко многим
    world_premier = models.DateField("Примьера в мире", default=date.today) # ставить значение времени
    budger = models.PositiveIntegerField('Бюджет', default=0, help_text='Указывать сумму в долларах')
    fees_in_usa = models.PositiveIntegerField(
        'Сборы в сша', default=0, help_text='Укажите сумму в долларах'
    )
    fees_in_world = models.PositiveIntegerField(
        'Сборы в мире', default=0, help_text='Укажите сумму в долларх'
    )

    category = models.ForeignKey(
        Category, verbose_name='Категория', on_delete=models.SET_NULL, null=True
    ) # ForeignKey - отношение многих к одному

    url = models.SlugField(max_length=150, unique=True) # SlugField - используется   для url(s)
    draft = models.BooleanField('Черновик', default=False)

    # Возвращает  значение в виде строки
    def __str__(self):
        return self.title
    

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={'slug': self.url})



    # Мета данные которые связываются с базой данных 
    class Meta:
        verbose_name = "Фильм " # ед. число 
        verbose_name_plural = "Фильм" 


class MovieShort(models.Model):

    # Отрывки из фильма

    title = models.CharField('Название', max_length=150)
    descriprions = models.TextField('Описания ') # TextFiled - текстовое поле 
    imgae = models.ImageField('Изоброжения ', upload_to='movie_shorts/') # сохроняет изоброженияв дериктории movie_shorts
    movie = models.ForeignKey(Movie, verbose_name='Фильм', on_delete=models.CASCADE)    # ForeignKey - отношение многих к одному


    # Возвращает  значение в виде строки
    def __str__(self):
        return self.title
    

    # Мета данные которые связываются с базой данных 
    class Meta:
        verbose_name = "Кадры из фильма" # ед. число 
        verbose_name_plural = "Кадры из фильма" 


class RatingStar(models.Model):

    # рейтинг в виде звезд

    value = models.SmallIntegerField('Значение', default=0)

    def __str__(self):
        return self.value
    
    class Meta:
        verbose_name = "Звезда рейтинга" # ед. число 
        verbose_name_plural = "Звезда рейтинга" 

class Rating(models.Model):

    # рейтинг фильма

    ip = models.CharField('IP адрес', max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name='звезда')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name='фильм')


    def __str__(self):
        return f'{self.star} - {self.movie}'
    
    class Meta:
        verbose_name = "Рейтинг" # ед. число 
        verbose_name_plural = "Рейтинг" 

class Reviews(models.Model):

    email = models.EmailField()
    name = models.CharField('Имя', max_length=150)
    text = models.TextField('Сообщение', max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name='Родитель', on_delete=models.SET_NULL, blank=True, null=True
    )

    movie = models.ForeignKey(Movie, verbose_name='Фильм', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} - {self.movie}'
    
    class Meta:
        verbose_name = "Отзыв" # ед. число 
        verbose_name_plural = "Отзыв" 

django_movie/movie/forms.py
from django import forms
from .models import Reviews
from django.forms import Textarea, TextInput, EmailInput


class ReviewForm(forms.ModelForm):
    '''''Форма для отзыва'''


    class Meta:
        model = Reviews
        fields = ("name", "email", "text")



   

django_movie/movie/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.views.generic import ListView, DetailView
from .models import Movie
from .forms import ReviewForm


class MoviesView(ListView):
    """Список фильмов """

    model = Movie
    queryset = Movie.objects.filter(draft=False)
    template_name = "movie/movies.html"
    
class MovieDeteilView(DetailView):
    """Полное описание фильма"""

    model = Movie
    slug_field = "url"


class AddReview(View):
    # отзывы

    def post(self, request, pk):
        print(request.POST)
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.movie = movie
            form.save()
        return redirect("/")
    


django_movie/movie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <!-- //Meta tag Keywords -->
    <title>{% block title %} {% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- //Meta tag Keywords -->
    <!-- Custom-Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Bootstrap-Core-CSS -->
    <!--/ Style-CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
    <!--// Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <!-- //font-awesome-icons -->
    <!-- /Fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700"
          rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900"
          rel="stylesheet">
    <!-- //Fonts -->
</head>
<body>
<div id="page" class="page">
    <div class="main-banner bg {% block header %}  {% endblock header %}" id="home">
        {% include 'include/header.html' %}
    </div>
    <ol class="breadcrumb editContent">
        <li class="breadcrumb-item">
            <a href="index.html" class="editContent">Home</a>
        </li>
        <li class="breadcrumb-item active editContent">Single Page</li>
    </ol>
    {% block content %}

    {% endblock content %}
    {% include 'include/footer.html' %}
</div>
</body>
</html>

django_movie/movie/templates/include/footer.html
<footer class="editContent">
    <div class="container">
        <div class="row footer-top">
            <div class="col-lg-4 footer-grid_section_w3layouts">
                <h2 class="logo-2 mb-lg-4 mb-3">
                    <a href="index.html" class="editContent">
                                <span class="fa" aria-hidden="true">
                                    Django School
                                </span>
                    </a>
                </h2>
                <p class="editContent">
                    Канал для программистов и людей, которые хотят развиваться в сфере IT.
                    Видео уроки по python 3, Django 2, Django 3, JavaScript, Vue.js, HTML, CSS
                    и многое другое.
                </p>
                <h4 class="sub-con-fo ad-info my-4 editContent">Catch on Social</h4>
                <ul class="w3layouts_social_list media-soc list-unstyled">
                    <li>
                        <a href="#" class="w3pvt_facebook editContent">
                            <span class="fa fa-facebook-f"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_twitter editContent">
                            <span class="fa fa-twitter"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_dribble editContent">
                            <span class="fa fa-dribbble"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="w3pvt_google editContent">
                            <span class="fa fa-google-plus"></span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-8 footer-right">
                <div class="w3layouts-news-letter">
                    <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">
                        Newsletter</h3>

                    <p class="editContent">By subscribing to our mailing list you will always
                        get latest news and updates from us.</p>
                    <form action="#" method="post" class="w3layouts-newsletter">
                        <input type="email" name="Email" class="editContent"
                               placeholder="Enter your email..." required="">
                        <button class="btn1 btn"><span class="fa fa-paper-plane-o"
                                                       aria-hidden="true"></span></button>

                    </form>
                </div>
                <div class="row mt-lg-4 bottom-w3layouts-sec-nav mx-0">
                    <div class="col-md-4 footer-grid_section_w3layouts">
                        <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">
                            Разделы</h3>
                        <ul class="list-unstyled w3layouts-icons">
                            <li>
                                <a href="index.html" class="editContent">Главная</a>
                            </li>
                            <li>
                                <a href="about.html" class="editContent">Категории</a>
                            </li>
                            <li>
                                <a href="contact.html" class="editContent">Контакты</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4 footer-grid_section_w3layouts">
                        <!-- social icons -->
                        <div class="agileinfo_social_icons">
                            <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3">
                                Pages</h3>
                            <ul class="list-unstyled w3layouts-icons">

                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                                <li>
                                    <a href="#" class="editContent">About Us</a>
                                </li>
                            </ul>
                        </div>
                        <!-- social icons -->
                    </div>
                    <div class="col-md-4 footer-grid_section_w3layouts my-md-0 my-5">
                        <h3 class="footer-title text-uppercase text-wh mb-lg-4 mb-3 editContent">
                            Contact Info</h3>
                        <div class="contact-info">
                            <div class="footer-address-inf my-4">
                                <h4 class="ad-info mb-2 editContent">Email </h4>
                                <p class="editContent"><a href="mailto:info@example.com">info@example.com</a>
                                </p>
                            </div>
                            <div class="footer-address-inf">
                                <h4 class="ad-info mb-2 editContent">Location</h4>
                                <p class="editContent">New York City</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- //footer -->
<div class="cpy-right py-3">
    <div class="container">
        <div class="row">
            <p class="col-md-10 text-left">© 2019 DjangoMovie. All rights reserved | Design by
                <a href="https://djangochannel.com"> DJANGO SCHOOL.</a>
            </p>
            <!-- move top icon -->
            <a href="#home" class="move-top text-right col-md-2"><span
                    class="fa fa-long-arrow-up" aria-hidden="true"></span></a>
            <!-- //move top icon -->
        </div>
    </div>
</div>

django_movie/movie/templates/include/header.html
<header class="header">
    <div class="container-fluid px-lg-5">
        <!-- nav -->
        <nav class="py-4">
            <div id="logo">
                <h1><a href="index.html" class="editContent"
                       style="outline: none; outline-offset: -2px; cursor: inherit; color: rgb(255, 255, 255); font-size: 40px; background-color: rgba(0, 0, 0, 0); font-family: Source Sans Pro;, sans-serif;">DjangoMovie</a>
                </h1>
            </div>

            <label for="drop" class="toggle">Menu</label>
            <input type="checkbox" id="drop">
            <ul class="menu mt-2">
                <li class="active"><a href="index.html">Главная</a></li>
                <li>
                    <!-- First Tier Drop Down -->
                    <label for="drop-2" class="toggle">Категории <span
                            class="fa fa-angle-down" aria-hidden="true"></span> </label>
                    <a href="#">Категории <span class="fa fa-angle-down"
                                                aria-hidden="true"></span></a>
                    <input type="checkbox" id="drop-2">
                    <ul>
                        <li><a href="moviesingle.html">Фильмы</a></li>
                        <li><a href="moviesingle.html">Сериалы</a></li>
                        <li><a href="moviesingle.html">Мультфильмы</a></li>
                    </ul>
                </li>
                <li><a href="contact.html"
                       style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Вход</a>
                </li>
            </ul>
        </nav>
        <!-- //nav -->
    </div>
</header>
<!-- //header -->
<!--/banner-->
<div class="banner-info">
    <p class="editContent">лучший сайт на django 3</p>
    <h3 class="mb-4 editContent">Все о кино</h3>
    <div class="ban-buttons">


    </div>
</div>
<!--// banner-inner -->

django_movie/movie/templates/movie/base.html
{% extends 'base.html' %}
{% block title %} {% endblock title %}
{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent"
             style="padding-left: 3rem; padding-right: 3rem;">
        {% block container %}
            <div class="container-fluid py-md-3">
        {% endblock container %}
        <div class="row">
            {% block sidebar %}
                <div class="side-bar col-lg-3">
            {% endblock sidebar %}
            {% include 'include/sidebar.html' %}
            </div>
            {% block movie %}
            {% endblock movie %}
        </div>
        </div>
    </section>
{% endblock content %}

django_movie/movie/templates/movie/movie_detail.html
{% extends 'movie/base.html' %}
{% block title %} {{ movie.title }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li style="list-style: none">
                        <span><b>Год:</b> {{ movie.year }}</span></li>
                    <li style="list-style: none">
                        <span><b>Страна:</b> {{ movie.country }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Слоган:</b> {{ movie.tagline }}</span>
                    </li>
                    <li style="list-style: none">
                                    <span><b>Режиссер:</b>
                                        {% for director in movie.directors.all %}
                                            {{ director.name }}
                                        {% endfor %}
                                    </span>
                    </li>
                    <li style="list-style: none"><span><b>Актеры:</b>
                        {% for actor in movie.actors.all %}
                            {{ actor.name }}
                        {% endfor %}
                                </span>
                    </li>
                    <li style="list-style: none"><span><b>Жанр:</b>
                        {% for genre in movie.genres.all %}
                            {{ genre.name }}
                        {% endfor %}
                                    </span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Премьера в мире:</b> {{ movie.world_premiere }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Бюджет:</b> ${{ movie.budget }}</span></li>
                    <li style="list-style: none">
                        <span><b>Сборы в США:</b> ${{ movie.fees_in_usa }}</span></li>
                    <li style="list-style: none">
                        <span><b>Сборы в мире:</b> ${{ movie.fess_in_world }}</span>
                    </li>
                    <li style="list-style: none">
                        <a href="#"><b>Рейтинг:</b>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="editContent"
                                  style="outline: none; cursor: inherit;">5.0</span>
                        </a>
                    </li>
                    <div class="share-desc">
                        <div class="share">
                            <h4 class="editContent"
                                style="outline: none; cursor: inherit;">
                                Share:</h4>
                            <ul class="w3layouts_social_list list-unstyled">
                                <li>
                                    <a href="#" class="w3pvt_facebook editContent"
                                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-facebook-f"
                                                      style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_twitter editContent"
                                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-twitter"
                                                      style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_dribble editContent"
                                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-dribbble"
                                                      style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="clearfix"></div>
                    </div>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                О фильме {{ movie.title }} 
            </h3>
            <h6>{{ movie.descriprions }}</h6>
            <p>

                {% for image in movie.movieshort_set.all %}
                <img src="{{ image.imgae.url }}" class="img-fluid" alt="{{ imgae.description }}">
                {% endfor %}
            
            </p>
            <p class="editContent" style="outline: none; cursor: inherit;">
                {{ movie.description }}
            </p>
            <p class="mt-3 italic-blue editContent"
               style="outline: none; cursor: inherit;">
                <iframe width="560" height="315"
                        src="https://www.youtube.com/embed/A36LahZNUiE?controls=0"
                        frameborder="0" allow="accelerometer; autoplay;
                                                                           encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen>

                </iframe>
            </p>
        </div>
        <hr>
        <div class="row">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">
                    <h3 class="editContent" style="outline: none; cursor: inherit;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;">02</span>Оставить
                        отзыв</h3>
                    <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4">
                        {% csrf_token %}
                        <div class="form-group editContent">
                            <label for="contactcomment" class="editContent">
                                Ваш комментарий *
                            </label>
                            <textarea class="form-control border" rows="5" name="text"
                                      id="contactcomment" required=""></textarea>
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent">
                                <label for="contactusername" class="editContent">
                                    Имя *
                                </label>
                                <input type="text" class="form-control border" name="name"
                                       id="contactusername" required="">
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent">
                                <label for="contactemail" class="editContent">
                                    Email *
                                </label>
                                <input type="email" class="form-control border" name="email"
                                       id="contactemail" required="">
                            </div>
                        </div>
                        <button type="submit"
                                class="mt-3 btn btn-success btn-block py-3">
                            Отправить
                        </button>
                    </form>
                </div>
                <!--  //contact form grid ends here -->
            </div>
        </div>
        {% for review in movie.reviews_set.all %}
            <div class="media py-5">
                <img src="bundles/images/te2.jpg" class="mr-3 img-fluid" alt="image">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">
                        {{ review.name }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                    <!-- <div class="media mt-5 editContent"
                         style="outline: none; cursor: inherit;">
                        <a class="pr-3" href="#">
                            <img src="bundles/images/te1.jpg" class="img-fluid "
                                 alt="image" style="outline: none; cursor: inherit;">
                        </a>
                        <div class="media-body">
                            <h5 class="mt-0 editContent"
                                style="outline: none; cursor: inherit;">Leia Organa</h5>
                            <p class="mt-2 editContent"
                               style="outline: none; cursor: inherit;"> Cras sit amet
                                nibh libero, in gravida nulla. Nulla vel metus
                                scelerisque ante sollicitudin. Cras purus odio,
                                vestibulum in vulputate at, tempus viverra turpis. Fusce
                                condimentum nunc ac nisi vulputate fringilla..</p>
                        </div>
                    </div> -->
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock movie %}